### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by friggog** [EmbodiedCognition/py-c3d#46]
Hitting this on install of latest version:

```
Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2857, in get_entry_map
    ep_map = self._ep_map
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 228, in _main
    status = self.run(options, args)
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 182, in wrapper
    return func(self, options, args)
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 406, in run
    pycompile=options.compile,
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
    pycompile=pycompile,
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 822, in install
    requested=self.user_supplied,
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 860, in install_wheel
    requested=requested,
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 662, in _install_wheel
    console, gui = get_entrypoints(distribution)
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_internal/operations/install/wheel.py", line 156, in get_entrypoints
    console = distribution.get_entry_map('console_scripts')
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2860, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2535, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2513, in parse_group
    ep = cls.parse(line, dist)
  File "/azureml-envs/azureml_05625119c63857e91b504d23cd268824/lib/python3.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2491, in parse
    raise ValueError(msg, src)
ValueError: ("EntryPoint must be in 'name=module:attrs [extras]' format", 'c3d-metatdata=scripts.c3d_metatdata:main()')
```

**Comment by AKuederle** [comment]
Damn... I didn't properly test the installation of the wheel after packaging.

Should work now. When I switched to poetry, I didn't realise, that poetry expects the script files that are packaged to be part of the package itself.

I changed that now (scripts is now a subfolder of c3d) and things should work now. I created a patch release 0.5.1
